### ISSUE TITLE
白屏

### ISSUE THREAD

**Issue by luyongfugx** [liuduanfei/player#1]
按照你的步骤，已经把资源放到flash了，并且art_pi_bootloader和art_pi_wifi 这两个工程都下载到板子上了还是白屏，有可能什么问题

**Comment by liuduanfei** [comment]
看一下打印的log



---原始邮件---
发件人: "luyongfugx"<notifications@github.com&gt;
发送时间: 2021年1月15日(周五) 上午10:58
收件人: "liuduanfei/player"<player@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [liuduanfei/player] 白屏 (#1)




 
按照你的步骤，已经把资源放到flash了，并且art_pi_bootloader和art_pi_wifi 这两个工程都下载到板子上了还是白屏，有可能什么问题

**Comment by luyongfugx** [comment]
可以了，要插着sdk卡
